[package]
name = "island-app"
description = "Top Island Tauri application shell"
version.workspace = true
edition.workspace = true

[build-dependencies]
tauri-build = { version = "2", features = [] }

[lib]
name = "island_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
island-core = { path = "../crates/island-core" }
island-windows = { path = "../crates/island-windows" }
island-wechat = { path = "../crates/island-wechat" }
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
ureq = { version = "3", features = ["json"] }
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_System_Registry",
    "Win32_System_SystemInformation",
] }
tauri-plugin-updater = "2.11.0"

[lints]
workspace = true
